# Generated by Django 3.1.7 on 2022-12-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuccessfulRecharges',
            new_name='SuccessfulRecharge',
        ),
    ]
